version: '3.8'

services:
  bot:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:123@db:5432/matchbot
      - BOT_TOKEN=8332081864:AAET6VuCm1MASQ_l2zbvGCQPyzvNB7dT1iM
      - TELEGRAM_BOT_TOKEN=8332081864:AAET6VuCm1MASQ_l2zbvGCQPyzvNB7dT1iM
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: matchbot
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
