name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
         username: ksunnnwy
         password: TrsbDfZ5W5jcnEs

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ksunnnwy/matchbot:latest

   - name: Deploy container
      run: |
        docker pull ksunnnwy/matchbot:latest
        docker stop matchbot || true
        docker rm matchbot || true
        docker run -d \
          --name matchbot \
          -e BOT_TOKEN=TrsbDfZ5W5jcnEs \
          ksunnnwy/matchbot:latest